# Generated by Django 2.2.6 on 2019-10-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unix_ts', models.IntegerField()),
                ('date_ts', models.DateTimeField()),
            ],
        ),
    ]
